import Link from "next/link";
import SiteShell from "../pages/SiteShell";
import ReadingProgress from "../../insights/[slug]/ReadingProgress";
import InsightCover from "./InsightCover";
import { InsightCard } from "./InsightCard";
import "./insights.css";
import { articleSchema } from "./postMetadata";

export default function ArticlePage({ post, related }) {
  const url = `https://creaweb.co.uk/${post.slug}`;
  const author = post.author || "Bornor Bang";
  return <SiteShell page="insight-detail"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(articleSchema(post)).replace(/</g, "\\u003c") }} /><ReadingProgress /><header className="ij-article-header sp-shell"><nav className="sp-breadcrumb" aria-label="Breadcrumb"><Link href="/">Home</Link><span aria-hidden="true">/</span><Link href="/insights">Insights</Link><span aria-hidden="true">/</span><span>{post.category || "General"}</span></nav><div className="ij-meta"><span className="ij-category">{post.category || "General"}</span><span>{post.issue || "From the studio journal"}</span></div><h1>{post.title}</h1><div className="ij-article-byline"><span className="ij-avatar" aria-hidden="true">{author[0]}</span><span>By <strong>{author}</strong></span><span>{post.date}</span><span>{post.readTime}</span><a href="#article-body" className="sp-text-link">Start reading ↓</a></div><div className="ij-article-cover"><InsightCover post={post} eager /></div></header><div className="sp-shell sp-section ij-reading-layout"><article id="article-body"><p className="ij-excerpt">{post.excerpt}</p><div className="ij-prose" dangerouslySetInnerHTML={{__html:post.content || "<p>Content coming soon.</p>"}} /><div className="ij-tags" aria-label="Article topics">{(Array.isArray(post.tags) && post.tags.length ? post.tags : [post.category || "General"]).map((tag,i)=><span key={`${tag}-${i}`}>{tag}</span>)}</div><Link className="sp-text-link ij-back-link" href="/insights">← Back to all insights</Link></article><aside className="ij-sidebar"><div className="ij-author-card"><span className="cw-label">Behind the words</span><div className="ij-author"><span className="ij-avatar" aria-hidden="true">{author[0]}</span><div><span>Author</span><p>{author}</p></div></div><dl><div><dt>Published</dt><dd>{post.date}</dd></div><div><dt>Read time</dt><dd>{post.readTime}</dd></div><div><dt>Category</dt><dd>{post.category || "General"}</dd></div></dl></div><nav className="ij-share" aria-label="Share this article"><span className="cw-label">Share this article</span><a href={`https://twitter.com/intent/tweet?text=${encodeURIComponent(post.title)}&url=${encodeURIComponent(url)}`} target="_blank" rel="noopener noreferrer">Share on X (Twitter) ↗</a><a href={`https://www.linkedin.com/sharing/share-offsite/?url=${encodeURIComponent(url)}`} target="_blank" rel="noopener noreferrer">Share on LinkedIn ↗</a><a href={`mailto:?subject=${encodeURIComponent(post.title)}&body=${encodeURIComponent(url)}`}>Share by email ↗</a></nav></aside></div>{related.length>0 && <section className="ij-related"><div className="sp-shell sp-section"><div className="ij-related-heading"><div><span className="cw-label">Continue reading</span><h2>More food<br />for thought.</h2></div><Link className="sp-text-link" href="/insights">All insights ↗</Link></div><div className="ij-card-grid">{related.map(p=><InsightCard key={p.id ?? p.slug} post={p} />)}</div></div></section>}</SiteShell>;
}
